services:
  - type: web
    name: emotional-awareness-tracker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    region: oregon
    autoDeploy: true
